#!/usr/bin/env python
'''
Class#3
V. Create a script that checks the validity of an IP address.  The IP address
should be supplied on the command line.
    A. Check that the IP address contains 4 octets.
    B. The first octet must be between 1 - 223.
    C. The first octet cannot be 127.
    D. The IP address cannot be in the 169.254.X.X address space.
    E. The last three octets must range between 0 - 255.
    For output, print the IP and whether it is valid or not.
'''


import sys

if len(sys.argv) == 2:
	ip_address = sys.argv.pop()

	print "the ip address is %s" % ip_address

else :
	print " you have type the wrong argument"

octets = ip_address.split(".")

flag = True

while True :
	if len(octets) != 4 :
		flag = False 
		break

	if (int(octets[0]) == 0 ) or (int (octets[0]) > 223) :
		flag = False 
		break

	if (int(octets[0]) == 127) :
		flag = False 
		break

	if (int(octets[0]) == 169 and int(octets[1]) == 254) :
		flag = False
		break

	for octet in octets[1:] :
		if int(octet) >= 255 :
			flag = False
			break

	break

print ip_address
print flag
