#!/usr/bin/env python

'''

Class#2
I. Create a script that does the following
   A. Prompts the user to input an IP network.
       Notes:
       1. For simplicity the network is always assumed to be a /24 network
       2. The network can be entered in using one of the following three formats
10.88.17.0, 10.88.17., or 10.88.17
   B. Regardless of which of the three formats is used, store this IP network as
a list in the following format ['10', '88', '17', '0'] i.e. a list with four
octets (all strings), the last octet is always zero (a string).
       Hint: There is a way you can accomplish this using a list slice.
       Hint2: If you can't solve this question with a list slice, then try using
   C. Print the IP network out to the screen.
   D. Print a table that looks like the following (columns 20 characters in
width):
      NETWORK_NUMBER   FIRST_OCTET_BINARY      FIRST_OCTET_HEX
      88.19.107.0      0b1011000               0x58
'''

ip  = raw_input("please enter the ip address:")
print ip 

octet = ip.split(".")
print octet

octet1 = octet[:3]
print octet1 

octet1.append('0')


j = ".".join(octet1)
print j

first = octet1[0]
bin = bin(int(first))
hex1 = hex(int(first))

print ("NETWORK_NUMBER" + "   " + "FIRST_OCTET_BINARY" + "   " "FIRST_OCTET_HEX" )
print("%s" + "           " + "%s" + "             " + "%s") % (j,bin,hex1)
